# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.oper_status_options import OperStatusOptions  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestOperStatusOptions(unittest.TestCase):
    """OperStatusOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperStatusOptions(self):
        """Test OperStatusOptions"""
        # inst = OperStatusOptions()

if __name__ == '__main__':
    unittest.main()
