# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.retrieve_attributes200_response1 import RetrieveAttributes200Response1  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestRetrieveAttributes200Response1(unittest.TestCase):
    """RetrieveAttributes200Response1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RetrieveAttributes200Response1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveAttributes200Response1`
        """
        model = ngsi_ld_client.models.retrieve_attributes200_response1.RetrieveAttributes200Response1()  # noqa: E501
        if include_optional :
            return RetrieveAttributes200Response1(
                id = '', 
                type = 'AttributeList', 
                attribute_list = [
                    ''
                    ]
            )
        else :
            return RetrieveAttributes200Response1(
                id = '',
                type = 'AttributeList',
                attribute_list = [
                    ''
                    ],
        )
        """

    def testRetrieveAttributes200Response1(self):
        """Test RetrieveAttributes200Response1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
