# coding: utf-8

"""
    NGSI-LD OAS

    OpenAPI Specification for NGSI-LD API.

    The version of the OpenAPI document: 1.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_client.models.feature_properties_value import FeaturePropertiesValue

class TestFeaturePropertiesValue(unittest.TestCase):
    """FeaturePropertiesValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeaturePropertiesValue:
        """Test FeaturePropertiesValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeaturePropertiesValue`
        """
        model = FeaturePropertiesValue()
        if include_optional:
            return FeaturePropertiesValue(
                type = 'Property',
                value = None,
                observed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                unit_code = '',
                dataset_id = '',
                system_generated_attrs = ngsi_ld_client.models.system_generated_attributes.SystemGeneratedAttributes(
                    created_at = null, 
                    modified_at = null, 
                    deleted_at = null, ),
                instance_id = '',
                previous_value = None,
                object = '',
                previous_object = '',
                language_map = None,
                previous_language_map = None
            )
        else:
            return FeaturePropertiesValue(
        )
        """

    def testFeaturePropertiesValue(self):
        """Test FeaturePropertiesValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
