# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_client.api.context_source_registration_subscription_api import ContextSourceRegistrationSubscriptionApi


class TestContextSourceRegistrationSubscriptionApi(unittest.TestCase):
    """ContextSourceRegistrationSubscriptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContextSourceRegistrationSubscriptionApi()

    def tearDown(self) -> None:
        pass

    def test_create_csr_subscription(self) -> None:
        """Test case for create_csr_subscription

        Create subscription to Csource registration 
        """
        pass

    def test_query_csr_subscription(self) -> None:
        """Test case for query_csr_subscription

        Retrieval of list of subscriptions to Csource registrations 
        """
        pass

    def test_retrieve_csr_subscription(self) -> None:
        """Test case for retrieve_csr_subscription

        Retrieval of subscription to Csource registration by id 
        """
        pass

    def test_update_csr_subscription(self) -> None:
        """Test case for update_csr_subscription

        Csource registration subscription update by id 
        """
        pass


if __name__ == '__main__':
    unittest.main()
