# coding: utf-8

"""
    NGSI-LD OAS

    OpenAPI Specification for NGSI-LD API.

    The version of the OpenAPI document: 1.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_client.models.options_sys_attrs import OptionsSysAttrs

class TestOptionsSysAttrs(unittest.TestCase):
    """OptionsSysAttrs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptionsSysAttrs(self):
        """Test OptionsSysAttrs"""
        # inst = OptionsSysAttrs()

if __name__ == '__main__':
    unittest.main()
