# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.interface import Interface  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestInterface(unittest.TestCase):
    """Interface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Interface
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Interface`
        """
        model = ngsi_ld_client.models.interface.Interface()  # noqa: E501
        if include_optional :
            return Interface(
                id = '', 
                type = '', 
                scope = None, 
                location = None, 
                observation_space = None, 
                operation_space = None, 
                name = None, 
                description = ngsi_ld_client.models.description.Description(), 
                enabled = None, 
                link_up_down_trap_enable = None, 
                admin_status = None, 
                oper_status = None, 
                last_change = None, 
                if_index = None, 
                phys_address = None, 
                speed = None, 
                higher_layer_if = None, 
                lower_layer_if = None
            )
        else :
            return Interface(
                id = '',
                type = '',
                name = None,
                admin_status = None,
                oper_status = None,
                if_index = None,
        )
        """

    def testInterface(self):
        """Test Interface"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
