# coding: utf-8

"""
    ietf-intefaces@2018-02-20.yang

    OpenAPI schema for the ietf-intefaces@2018-02-20.yang YANG module  supported by a model-based network device.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.oper_status_options import OperStatusOptions  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestOperStatusOptions(unittest.TestCase):
    """OperStatusOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperStatusOptions(self):
        """Test OperStatusOptions"""
        # inst = OperStatusOptions()

if __name__ == '__main__':
    unittest.main()
