# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_client.api.temporal_context_information_provision_api import TemporalContextInformationProvisionApi  # noqa: E501


class TestTemporalContextInformationProvisionApi(unittest.TestCase):
    """TemporalContextInformationProvisionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemporalContextInformationProvisionApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_append_attrs_temporal(self) -> None:
        """Test case for append_attrs_temporal

        Temporal Representation of Entity Attribute instance addition   # noqa: E501
        """
        pass

    def test_delete_attr_instance_temporal(self) -> None:
        """Test case for delete_attr_instance_temporal

        Attribute Instance deletion by instance id   # noqa: E501
        """
        pass

    def test_delete_attrs_temporal(self) -> None:
        """Test case for delete_attrs_temporal

        Attribute from Temporal Representation of Entity deletion   # noqa: E501
        """
        pass

    def test_delete_temporal(self) -> None:
        """Test case for delete_temporal

        Temporal Representation of Entity deletion by id   # noqa: E501
        """
        pass

    def test_update_attrs_temporal(self) -> None:
        """Test case for update_attrs_temporal

        Attribute Instance update   # noqa: E501
        """
        pass

    def test_upsert_temporal(self) -> None:
        """Test case for upsert_temporal

        Temporal Representation of Entity creation   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
