# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.admin_status_options import AdminStatusOptions  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestAdminStatusOptions(unittest.TestCase):
    """AdminStatusOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdminStatusOptions(self):
        """Test AdminStatusOptions"""
        # inst = AdminStatusOptions()

if __name__ == '__main__':
    unittest.main()
