# coding: utf-8

"""
    NGSI-LD OAS

    OpenAPI Specification for NGSI-LD API.

    The version of the OpenAPI document: 1.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_client.models.query_temporal200_response_inner import QueryTemporal200ResponseInner

class TestQueryTemporal200ResponseInner(unittest.TestCase):
    """QueryTemporal200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryTemporal200ResponseInner:
        """Test QueryTemporal200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryTemporal200ResponseInner`
        """
        model = QueryTemporal200ResponseInner()
        if include_optional:
            return QueryTemporal200ResponseInner(
                id = '',
                type = None,
                scope = None,
                location = {
                    'key' : null
                    },
                observation_space = {
                    'key' : null
                    },
                operation_space = {
                    'key' : null
                    },
                system_generated_attrs = ngsi_ld_client.models.system_generated_attributes.SystemGeneratedAttributes(
                    created_at = null, 
                    modified_at = null, 
                    deleted_at = null, )
            )
        else:
            return QueryTemporal200ResponseInner(
                id = '',
                type = None,
        )
        """

    def testQueryTemporal200ResponseInner(self):
        """Test QueryTemporal200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
