# coding: utf-8

"""
    ietf-intefaces@2018-02-20.yang

    OpenAPI schema for the ietf-intefaces@2018-02-20.yang YANG module  supported by a model-based network device.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.if_index_all_of import IfIndexAllOf  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestIfIndexAllOf(unittest.TestCase):
    """IfIndexAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IfIndexAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IfIndexAllOf`
        """
        model = ngsi_ld_client.models.if_index_all_of.IfIndexAllOf()  # noqa: E501
        if include_optional :
            return IfIndexAllOf(
                value = 56
            )
        else :
            return IfIndexAllOf(
                value = 56,
        )
        """

    def testIfIndexAllOf(self):
        """Test IfIndexAllOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
