# coding: utf-8

"""
    ietf-intefaces@2018-02-20.yang

    OpenAPI schema for the ietf-intefaces@2018-02-20.yang YANG module  supported by a model-based network device.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.is_part_of import IsPartOf  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestIsPartOf(unittest.TestCase):
    """IsPartOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IsPartOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsPartOf`
        """
        model = ngsi_ld_client.models.is_part_of.IsPartOf()  # noqa: E501
        if include_optional :
            return IsPartOf(
                type = 'Relationship', 
                object = '', 
                observed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                dataset_id = ''
            )
        else :
            return IsPartOf(
                type = 'Relationship',
                object = '',
        )
        """

    def testIsPartOf(self):
        """Test IsPartOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
