# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import ngsi_ld_client
from ngsi_ld_client.api.context_information_consumption_api import ContextInformationConsumptionApi  # noqa: E501
from ngsi_ld_client.rest import ApiException


class TestContextInformationConsumptionApi(unittest.TestCase):
    """ContextInformationConsumptionApi unit test stubs"""

    def setUp(self):
        self.api = ngsi_ld_client.api.context_information_consumption_api.ContextInformationConsumptionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_query_batch(self):
        """Test case for query_batch

        Query entities based on POST.  # noqa: E501
        """
        pass

    def test_query_entity(self):
        """Test case for query_entity

        Query entities   # noqa: E501
        """
        pass

    def test_query_subscription(self):
        """Test case for query_subscription

        Retrieve list of Subscriptions  # noqa: E501
        """
        pass

    def test_retrieve_attr_info(self):
        """Test case for retrieve_attr_info

        Retrieve Available Attribute Information  # noqa: E501
        """
        pass

    def test_retrieve_attributes(self):
        """Test case for retrieve_attributes

        Retrieve Available Attributes  # noqa: E501
        """
        pass

    def test_retrieve_entity(self):
        """Test case for retrieve_entity

        Entity retrieval by id   # noqa: E501
        """
        pass

    def test_retrieve_subscription(self):
        """Test case for retrieve_subscription

        Subscription retrieval by id  # noqa: E501
        """
        pass

    def test_retrieve_type_info(self):
        """Test case for retrieve_type_info

        Details about available entity type  # noqa: E501
        """
        pass

    def test_retrieve_types(self):
        """Test case for retrieve_types

        Retrieve available entity types  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
