# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import ngsi_ld_client
from ngsi_ld_client.api.jsonld_context_api_api import JSONLDContextAPIApi  # noqa: E501
from ngsi_ld_client.rest import ApiException


class TestJSONLDContextAPIApi(unittest.TestCase):
    """JSONLDContextAPIApi unit test stubs"""

    def setUp(self):
        self.api = ngsi_ld_client.api.jsonld_context_api_api.JSONLDContextAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_context(self):
        """Test case for create_context

        Add a user @context to the internal cache   # noqa: E501
        """
        pass

    def test_delete_context(self):
        """Test case for delete_context

        Delete one specific @context from internal cache, possibly re-inserting a freshly downloaded copy of it   # noqa: E501
        """
        pass

    def test_list_contexts(self):
        """Test case for list_contexts

        List all cached @contexts   # noqa: E501
        """
        pass

    def test_retrieve_context(self):
        """Test case for retrieve_context

        Serve one specific user @context   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
