# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.link_up_down_trap_enable_options import LinkUpDownTrapEnableOptions  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestLinkUpDownTrapEnableOptions(unittest.TestCase):
    """LinkUpDownTrapEnableOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkUpDownTrapEnableOptions(self):
        """Test LinkUpDownTrapEnableOptions"""
        # inst = LinkUpDownTrapEnableOptions()

if __name__ == '__main__':
    unittest.main()
