# coding: utf-8

"""
    ietf-intefaces@2018-02-20.yang

    OpenAPI schema for the ietf-intefaces@2018-02-20.yang YANG module  supported by a model-based network device.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.geometry_multi_line_string import GeometryMultiLineString  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestGeometryMultiLineString(unittest.TestCase):
    """GeometryMultiLineString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GeometryMultiLineString
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeometryMultiLineString`
        """
        model = ngsi_ld_client.models.geometry_multi_line_string.GeometryMultiLineString()  # noqa: E501
        if include_optional :
            return GeometryMultiLineString(
                type = 'MultiLineString', 
                coordinates = [
                    ngsi_ld_client.models.geometry/line_string.Geometry.LineString(
                        type = 'LineString', )
                    ]
            )
        else :
            return GeometryMultiLineString(
        )
        """

    def testGeometryMultiLineString(self):
        """Test GeometryMultiLineString"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
