# coding: utf-8

"""
    NGSI-LD OAS

    OpenAPI Specification for NGSI-LD API.

    The version of the OpenAPI document: 1.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_client.models.vocabulary_property import VocabularyProperty

class TestVocabularyProperty(unittest.TestCase):
    """VocabularyProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VocabularyProperty:
        """Test VocabularyProperty
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VocabularyProperty`
        """
        model = VocabularyProperty()
        if include_optional:
            return VocabularyProperty(
                type = 'VocabularyProperty',
                vocab = None,
                previous_vocab = None,
                observed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                dataset_id = '',
                system_generated_attrs = ngsi_ld_client.models.system_generated_attributes.SystemGeneratedAttributes(
                    created_at = null, 
                    modified_at = null, 
                    deleted_at = null, ),
                instance_id = ''
            )
        else:
            return VocabularyProperty(
        )
        """

    def testVocabularyProperty(self):
        """Test VocabularyProperty"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
