# coding: utf-8

"""
    ietf-intefaces@2018-02-20.yang

    OpenAPI schema for the ietf-intefaces@2018-02-20.yang YANG module  supported by a model-based network device.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.admin_status_options import AdminStatusOptions  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestAdminStatusOptions(unittest.TestCase):
    """AdminStatusOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdminStatusOptions(self):
        """Test AdminStatusOptions"""
        # inst = AdminStatusOptions()

if __name__ == '__main__':
    unittest.main()
