# coding: utf-8

"""
    NGSI-LD OAS

    OpenAPI Specification for NGSI-LD API.

    The version of the OpenAPI document: 1.7.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_client.models.vocabulary_property_previous_vocab import VocabularyPropertyPreviousVocab

class TestVocabularyPropertyPreviousVocab(unittest.TestCase):
    """VocabularyPropertyPreviousVocab unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VocabularyPropertyPreviousVocab:
        """Test VocabularyPropertyPreviousVocab
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VocabularyPropertyPreviousVocab`
        """
        model = VocabularyPropertyPreviousVocab()
        if include_optional:
            return VocabularyPropertyPreviousVocab(
            )
        else:
            return VocabularyPropertyPreviousVocab(
        )
        """

    def testVocabularyPropertyPreviousVocab(self):
        """Test VocabularyPropertyPreviousVocab"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
