# coding: utf-8

"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""

import unittest

import ngsi_ld_client
from ngsi_ld_client.model.geometry import Geometry


class TestGeometry(unittest.TestCase):
    """Geometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_Geometry(self):
        """Test Geometry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Geometry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
