# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import ngsi_ld_client
from ngsi_ld_client.api.context_source_discovery_api import ContextSourceDiscoveryApi  # noqa: E501
from ngsi_ld_client.rest import ApiException


class TestContextSourceDiscoveryApi(unittest.TestCase):
    """ContextSourceDiscoveryApi unit test stubs"""

    def setUp(self):
        self.api = ngsi_ld_client.api.context_source_discovery_api.ContextSourceDiscoveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_query_csr(self):
        """Test case for query_csr

        Discover Csource registrations   # noqa: E501
        """
        pass

    def test_retrieve_csr(self):
        """Test case for retrieve_csr

        Csource registration retrieval by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
