# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import ngsi_ld_client
from ngsi_ld_client.models.statistics_all_of import StatisticsAllOf  # noqa: E501
from ngsi_ld_client.rest import ApiException

class TestStatisticsAllOf(unittest.TestCase):
    """StatisticsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StatisticsAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatisticsAllOf`
        """
        model = ngsi_ld_client.models.statistics_all_of.StatisticsAllOf()  # noqa: E501
        if include_optional :
            return StatisticsAllOf(
                type = 'Statistics', 
                is_part_of = ngsi_ld_client.models.is_part_of.IsPartOf(), 
                discontinuity_time = ngsi_ld_client.models.discontinuity_time.DiscontinuityTime(), 
                in_octets = ngsi_ld_client.models.in_octets.InOctets(), 
                in_unicast_pkts = ngsi_ld_client.models.in_unicast_pkts.InUnicastPkts(), 
                in_broadcast_pkts = ngsi_ld_client.models.in_broadcast_pkts.InBroadcastPkts(), 
                in_multicast_pkts = ngsi_ld_client.models.in_multicast_pkts.InMulticastPkts(), 
                in_discards = ngsi_ld_client.models.in_discards.InDiscards(), 
                in_errors = ngsi_ld_client.models.in_errors.InErrors(), 
                in_unknown_protos = ngsi_ld_client.models.in_unknown_protos.InUnknownProtos(), 
                out_octets = ngsi_ld_client.models.out_octets.OutOctets(), 
                out_unicast_pkts = ngsi_ld_client.models.out_unicast_pkts.OutUnicastPkts(), 
                out_broadcast_pkts = ngsi_ld_client.models.out_broadcast_pkts.OutBroadcastPkts(), 
                out_multicast_pkts = ngsi_ld_client.models.out_multicast_pkts.OutMulticastPkts(), 
                out_discards = ngsi_ld_client.models.out_discards.OutDiscards(), 
                out_errors = ngsi_ld_client.models.out_errors.OutErrors()
            )
        else :
            return StatisticsAllOf(
        )
        """

    def testStatisticsAllOf(self):
        """Test StatisticsAllOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
