# coding: utf-8

"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""

from ngsi_ld_client.api_client import ApiClient
from ngsi_ld_client.api.batch_operations_api_endpoints.batch_entity_creation import BatchEntityCreation
from ngsi_ld_client.api.batch_operations_api_endpoints.batch_entity_delete import BatchEntityDelete
from ngsi_ld_client.api.batch_operations_api_endpoints.batch_entity_update import BatchEntityUpdate
from ngsi_ld_client.api.batch_operations_api_endpoints.batch_entity_upsert import BatchEntityUpsert


class BatchOperationsApi(
    BatchEntityCreation,
    BatchEntityDelete,
    BatchEntityUpdate,
    BatchEntityUpsert,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
