# coding: utf-8

"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""

from ngsi_ld_client.api_client import ApiClient
from ngsi_ld_client.api.subscriptions_api_endpoints.create_subscription import CreateSubscription
from ngsi_ld_client.api.subscriptions_api_endpoints.remove_subscription import RemoveSubscription
from ngsi_ld_client.api.subscriptions_api_endpoints.retrieve_subscription_by_id import RetrieveSubscriptionById
from ngsi_ld_client.api.subscriptions_api_endpoints.retrieve_subscriptions import RetrieveSubscriptions
from ngsi_ld_client.api.subscriptions_api_endpoints.update_subscription import UpdateSubscription


class SubscriptionsApi(
    CreateSubscription,
    RemoveSubscription,
    RetrieveSubscriptionById,
    RetrieveSubscriptions,
    UpdateSubscription,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
