# coding: utf-8

"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""

from ngsi_ld_client.api_client import ApiClient
from ngsi_ld_client.api.temporal_evolution_api_endpoints.add_temporal_entity_attrs import AddTemporalEntityAttrs
from ngsi_ld_client.api.temporal_evolution_api_endpoints.create_update_entity_temporal import CreateUpdateEntityTemporal
from ngsi_ld_client.api.temporal_evolution_api_endpoints.modify_entity_temporal_attr_instance import ModifyEntityTemporalAttrInstance
from ngsi_ld_client.api.temporal_evolution_api_endpoints.query_temporal_entities import QueryTemporalEntities
from ngsi_ld_client.api.temporal_evolution_api_endpoints.remove_entity_temporal_attr import RemoveEntityTemporalAttr
from ngsi_ld_client.api.temporal_evolution_api_endpoints.remove_entity_temporal_attr_instance import RemoveEntityTemporalAttrInstance
from ngsi_ld_client.api.temporal_evolution_api_endpoints.remove_entity_temporal_by_id import RemoveEntityTemporalById
from ngsi_ld_client.api.temporal_evolution_api_endpoints.retrieve_entity_temporal_by_id import RetrieveEntityTemporalById


class TemporalEvolutionApi(
    AddTemporalEntityAttrs,
    CreateUpdateEntityTemporal,
    ModifyEntityTemporalAttrInstance,
    QueryTemporalEntities,
    RemoveEntityTemporalAttr,
    RemoveEntityTemporalAttrInstance,
    RemoveEntityTemporalById,
    RetrieveEntityTemporalById,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
