# coding: utf-8

# flake8: noqa

"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from ngsi_ld_client.api_client import ApiClient

# import Configuration
from ngsi_ld_client.configuration import Configuration

# import exceptions
from ngsi_ld_client.exceptions import OpenApiException
from ngsi_ld_client.exceptions import ApiAttributeError
from ngsi_ld_client.exceptions import ApiTypeError
from ngsi_ld_client.exceptions import ApiValueError
from ngsi_ld_client.exceptions import ApiKeyError
from ngsi_ld_client.exceptions import ApiException
