# coding: utf-8

"""
    ETSI ISG CIM / NGSI-LD API

    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders  # noqa: E501

    The version of the OpenAPI document: latest
    Contact: NGSI-LD@etsi.org
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from ngsi_ld_client.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class NotificationParams(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    _required_property_names = set((
        'endpoint',
    ))
    
    
    class attributes(
        _SchemaValidator(
            unique_items=True,
            min_items=1,
        ),
        ListSchema
    ):
        
        
        class _items(
            _SchemaValidator(
                min_length=1,
            ),
            StrSchema
        ):
            pass
    format = StrSchema

    @classmethod
    @property
    def endpoint(cls) -> typing.Type['Endpoint']:
        return Endpoint
    
    
    class status(
        _SchemaEnumMaker(
            enum_value_to_name={
                "ok": "OK",
                "failed": "FAILED",
            }
        ),
        StrSchema
    ):
        
        @classmethod
        @property
        def OK(cls):
            return cls("ok")
        
        @classmethod
        @property
        def FAILED(cls):
            return cls("failed")
    
    
    class timesSent(
        _SchemaValidator(
            inclusive_minimum=1,
        ),
        NumberSchema
    ):
        pass
    lastNotification = DateTimeSchema
    lastFailure = DateTimeSchema
    lastSuccess = DateTimeSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        endpoint: endpoint,
        attributes: typing.Union[attributes, Unset] = unset,
        format: typing.Union[format, Unset] = unset,
        status: typing.Union[status, Unset] = unset,
        timesSent: typing.Union[timesSent, Unset] = unset,
        lastNotification: typing.Union[lastNotification, Unset] = unset,
        lastFailure: typing.Union[lastFailure, Unset] = unset,
        lastSuccess: typing.Union[lastSuccess, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'NotificationParams':
        return super().__new__(
            cls,
            *args,
            endpoint=endpoint,
            attributes=attributes,
            format=format,
            status=status,
            timesSent=timesSent,
            lastNotification=lastNotification,
            lastFailure=lastFailure,
            lastSuccess=lastSuccess,
            _configuration=_configuration,
            **kwargs,
        )

from ngsi_ld_client.model.endpoint import Endpoint
