# coding: utf-8

# flake8: noqa
"""
    ietf-intefaces@2018-02-20.yang

    OpenAPI schema for the ietf-intefaces@2018-02-20.yang YANG module  supported by a model-based network device.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from ngsi_ld_client.models.admin_status import AdminStatus
from ngsi_ld_client.models.admin_status_all_of import AdminStatusAllOf
from ngsi_ld_client.models.admin_status_options import AdminStatusOptions
from ngsi_ld_client.models.description import Description
from ngsi_ld_client.models.discontinuity_time import DiscontinuityTime
from ngsi_ld_client.models.enabled import Enabled
from ngsi_ld_client.models.enabled_all_of import EnabledAllOf
from ngsi_ld_client.models.entity_common import EntityCommon
from ngsi_ld_client.models.entity_common_scope import EntityCommonScope
from ngsi_ld_client.models.entity_common_type import EntityCommonType
from ngsi_ld_client.models.entity_fragment_input import EntityFragmentInput
from ngsi_ld_client.models.entity_fragment_input_all_of import EntityFragmentInputAllOf
from ngsi_ld_client.models.entity_input import EntityInput
from ngsi_ld_client.models.geo_property_common import GeoPropertyCommon
from ngsi_ld_client.models.geo_property_fragment_input import GeoPropertyFragmentInput
from ngsi_ld_client.models.geo_property_input import GeoPropertyInput
from ngsi_ld_client.models.geometry import Geometry
from ngsi_ld_client.models.geometry_line_string import GeometryLineString
from ngsi_ld_client.models.geometry_multi_line_string import GeometryMultiLineString
from ngsi_ld_client.models.geometry_multi_point import GeometryMultiPoint
from ngsi_ld_client.models.geometry_multi_polygon import GeometryMultiPolygon
from ngsi_ld_client.models.geometry_point import GeometryPoint
from ngsi_ld_client.models.geometry_polygon import GeometryPolygon
from ngsi_ld_client.models.higher_layer_if import HigherLayerIf
from ngsi_ld_client.models.higher_layer_if_all_of import HigherLayerIfAllOf
from ngsi_ld_client.models.if_index import IfIndex
from ngsi_ld_client.models.if_index_all_of import IfIndexAllOf
from ngsi_ld_client.models.in_broadcast_pkts import InBroadcastPkts
from ngsi_ld_client.models.in_discards import InDiscards
from ngsi_ld_client.models.in_errors import InErrors
from ngsi_ld_client.models.in_multicast_pkts import InMulticastPkts
from ngsi_ld_client.models.in_octets import InOctets
from ngsi_ld_client.models.in_unicast_pkts import InUnicastPkts
from ngsi_ld_client.models.in_unknown_protos import InUnknownProtos
from ngsi_ld_client.models.interface import Interface
from ngsi_ld_client.models.interface_all_of import InterfaceAllOf
from ngsi_ld_client.models.is_part_of import IsPartOf
from ngsi_ld_client.models.last_change import LastChange
from ngsi_ld_client.models.last_change_all_of import LastChangeAllOf
from ngsi_ld_client.models.link_up_down_trap_enable import LinkUpDownTrapEnable
from ngsi_ld_client.models.link_up_down_trap_enable_all_of import LinkUpDownTrapEnableAllOf
from ngsi_ld_client.models.link_up_down_trap_enable_options import LinkUpDownTrapEnableOptions
from ngsi_ld_client.models.lower_layer_if import LowerLayerIf
from ngsi_ld_client.models.name import Name
from ngsi_ld_client.models.name_all_of import NameAllOf
from ngsi_ld_client.models.oper_status import OperStatus
from ngsi_ld_client.models.oper_status_options import OperStatusOptions
from ngsi_ld_client.models.out_broadcast_pkts import OutBroadcastPkts
from ngsi_ld_client.models.out_discards import OutDiscards
from ngsi_ld_client.models.out_errors import OutErrors
from ngsi_ld_client.models.out_multicast_pkts import OutMulticastPkts
from ngsi_ld_client.models.out_octets import OutOctets
from ngsi_ld_client.models.out_unicast_pkts import OutUnicastPkts
from ngsi_ld_client.models.phys_address import PhysAddress
from ngsi_ld_client.models.phys_address_all_of import PhysAddressAllOf
from ngsi_ld_client.models.property_common import PropertyCommon
from ngsi_ld_client.models.property_fragment_input import PropertyFragmentInput
from ngsi_ld_client.models.property_input import PropertyInput
from ngsi_ld_client.models.relationship_common import RelationshipCommon
from ngsi_ld_client.models.relationship_fragment_input import RelationshipFragmentInput
from ngsi_ld_client.models.relationship_input import RelationshipInput
from ngsi_ld_client.models.speed import Speed
from ngsi_ld_client.models.statistics import Statistics
from ngsi_ld_client.models.statistics_all_of import StatisticsAllOf
