# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AdminStatusOptions(str, Enum):
    """
    Options for linkUp/linkDown SNMP notifications.
    """

    """
    allowed enum values
    """
    UP = 'up'
    DOWN = 'down'
    TESTING = 'testing'

    @classmethod
    def from_json(cls, json_str: str) -> AdminStatusOptions:
        """Create an instance of AdminStatusOptions from a JSON string"""
        return AdminStatusOptions(json.loads(json_str))


