# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictStr, conlist, validator

class EntityType(BaseModel):
    """
    5.2.25 This type represents the data needed to define the elements of the detailed entity type list representation as mandated by clause 4.5.11. 
    """
    id: StrictStr = Field(..., description="Fully Qualified Name (FQN) of the entity type being described. ")
    type: StrictStr = Field(..., description="JSON-LD @type. ")
    type_name: StrictStr = Field(..., alias="typeName", description="Name of the entity type, short name if contained in @context. ")
    attribute_names: conlist(StrictStr) = Field(..., alias="attributeNames", description="List containing the names of attributes that instances of the entity type can have. ")
    __properties = ["id", "type", "typeName", "attributeNames"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('EntityType'):
            raise ValueError("must be one of enum values ('EntityType')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EntityType:
        """Create an instance of EntityType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EntityType:
        """Create an instance of EntityType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EntityType.parse_obj(obj)

        _obj = EntityType.parse_obj({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "type_name": obj.get("typeName"),
            "attribute_names": obj.get("attributeNames")
        })
        return _obj

