# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, conlist, validator
from ngsi_ld_client.models.list_contexts200_response_one_of_inner import ListContexts200ResponseOneOfInner
from ngsi_ld_client.models.list_contexts200_response_one_of_inner1 import ListContexts200ResponseOneOfInner1
from typing import Any, List
from pydantic import StrictStr, Field

LISTCONTEXTS200RESPONSE_ONE_OF_SCHEMAS = ["List[ListContexts200ResponseOneOfInner1]", "List[ListContexts200ResponseOneOfInner]"]

class ListContexts200Response(BaseModel):
    """
    ListContexts200Response
    """
    # data type: List[ListContexts200ResponseOneOfInner]
    oneof_schema_1_validator: Optional[conlist(ListContexts200ResponseOneOfInner)] = None
    # data type: List[ListContexts200ResponseOneOfInner1]
    oneof_schema_2_validator: Optional[conlist(ListContexts200ResponseOneOfInner1)] = None
    actual_instance: Any
    one_of_schemas: List[str] = Field(LISTCONTEXTS200RESPONSE_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs):
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ListContexts200Response.construct()
        error_messages = []
        match = 0
        # validate data type: List[ListContexts200ResponseOneOfInner]
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: List[ListContexts200ResponseOneOfInner1]
        try:
            instance.oneof_schema_2_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ListContexts200Response with oneOf schemas: List[ListContexts200ResponseOneOfInner1], List[ListContexts200ResponseOneOfInner]. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ListContexts200Response with oneOf schemas: List[ListContexts200ResponseOneOfInner1], List[ListContexts200ResponseOneOfInner]. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> ListContexts200Response:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> ListContexts200Response:
        """Returns the object represented by the json string"""
        instance = ListContexts200Response.construct()
        error_messages = []
        match = 0

        # deserialize data into List[ListContexts200ResponseOneOfInner]
        try:
            # validation
            instance.oneof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_1_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into List[ListContexts200ResponseOneOfInner1]
        try:
            # validation
            instance.oneof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_2_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ListContexts200Response with oneOf schemas: List[ListContexts200ResponseOneOfInner1], List[ListContexts200ResponseOneOfInner]. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ListContexts200Response with oneOf schemas: List[ListContexts200ResponseOneOfInner1], List[ListContexts200ResponseOneOfInner]. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())

