# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from ngsi_ld_client.models.property_input import PropertyInput

from pydantic import BaseModel, Field, StrictStr, validator

class OperStatusAllOf(PropertyInput):
    """
    OperStatusAllOf
    """
    value: StrictStr = Field(...)
    __properties = ["value"]

    @validator('value')
    def value_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('up', 'down', 'testing', 'unknown', 'dormant', 'not-present', 'lower-layer-down'):
            raise ValueError("must be one of enum values ('up', 'down', 'testing', 'unknown', 'dormant', 'not-present', 'lower-layer-down')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OperStatusAllOf:
        """Create an instance of OperStatusAllOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OperStatusAllOf:
        """Create an instance of OperStatusAllOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OperStatusAllOf.parse_obj(obj)

        _obj = OperStatusAllOf.parse_obj({
            "value": obj.get("value")
        })
        return _obj

