# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.  # noqa: E501

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class OperStatusOptions(str, Enum):
    """
    Options for the operational state of the interface.
    """

    """
    allowed enum values
    """
    UP = 'up'
    DOWN = 'down'
    TESTING = 'testing'
    UNKNOWN = 'unknown'
    DORMANT = 'dormant'
    NOT_MINUS_PRESENT = 'not-present'
    LOWER_MINUS_LAYER_MINUS_DOWN = 'lower-layer-down'

    @classmethod
    def from_json(cls, json_str: str) -> OperStatusOptions:
        """Create an instance of OperStatusOptions from a JSON string"""
        return OperStatusOptions(json.loads(json_str))


